// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Department
{
    public string DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public virtual ICollection<Student> Student { get; set; } = new List<Student>();
}