// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LoanDetail
{
    public int LoanDetailId { get; set; }

    public int? BookId { get; set; }

    public int? LoanId { get; set; }

    public bool? Status { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public virtual Book Book { get; set; }

    public virtual Loan Loan { get; set; }
}