// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Student
{
    public string StudentId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Loan> Loan { get; set; } = new List<Loan>();
}